# Usa l'immagine base di Ruby
FROM ruby:2.7

# Imposta la directory di lavoro
WORKDIR /code

# Copia tutti i file del contesto corrente nella directory di lavoro del container
COPY . /code

# Comando per eseguire il file Ruby
CMD ["ruby", "/code/code.rb"]
